### ISSUE TITLE
Only the first go.target is exported

### ISSUE THREAD

**Issue by matthewmcnew** [paketo-buildpacks/go-mod#17]
If an app has multiple targets, then all of the targets will be built but, only the first target will actually be exported in the resulting image.

For example in an app with the following buildpack.yaml, only `binaryone` will be in the resulting image. 

```
go:
  targets: ["./cmd/binaryone", "./cmd/binarytwo", "./cmd/binarythree"]
```

**Comment by sukhil-suresh** [comment]
Ran into a similar problem, when using the `pack` cli to build an app with multiple binaries

```
➜  pack build test-image -B gcr.io/paketo-buildpacks/builder:tiny -e BP_GO_TARGETS="./cmd/webhook:./cmd/manager"
```

The generated image contains only the `webhook` binary (and is missing the `manager` binary)
